Fix build error
Fix of order of inclusion of files. Type YYSTYPE is used before inclusion
of parser.h. This leads to the following error:

```
In file included from kafel.c:28:0:
lexer.h:301:1: error: unknown type name 'YYSTYPE'
 YYSTYPE * kafel_yyget_lval (yyscan_t yyscanner );
 ^~~~~~~
lexer.h:303:24: error: unknown type name 'YYSTYPE'
```

Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>